query($catergoryName: Mixed) {
    level1: taxonomyContent(where: { column: TITLE, value: $catergoryName }) {
        children {
            id
            title
            children {
                title
                children {
                    title
                }
            }
        }
    }
}
