query {
    users(orderBy: { column: CREATED_AT, order: DESC }) {
        data {
            id
            name
            email
            created_at
            phone_no
            gender
            phone_verified_at
            email_verified_at
        }
    }
}
